// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package packet

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson171f2b04DecodeGithubComReisub1GoNewServerPacket(in *jlexer.Lexer, out *Packet) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson171f2b04EncodeGithubComReisub1GoNewServerPacket(out *jwriter.Writer, in Packet) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Packet) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson171f2b04EncodeGithubComReisub1GoNewServerPacket(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Packet) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson171f2b04EncodeGithubComReisub1GoNewServerPacket(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Packet) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson171f2b04DecodeGithubComReisub1GoNewServerPacket(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Packet) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson171f2b04DecodeGithubComReisub1GoNewServerPacket(l, v)
}
